w5d1/music-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/bands')

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:show, :new, :create] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy,]

  resources :notes, only: [:create, :destroy]
end

w5d1/music-app/app/models/track.rb
class Track < ApplicationRecord
  # N.B. Remember, Rails 5 automatically validates the presence of
  # belongs_to associations, so we can leave the validation of albums
  # out here.
  validates :lyrics, :name, :ord, presence: true
  # can't use presence validation with boolean field
  validates :bonus, inclusion: { in: [true, false] }
  validates :ord, uniqueness: { scope: :album_id }

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes,
    dependent: :destroy

  after_initialize :set_defaults

  def set_defaults
    self.bonus ||= false
  end
end

w5d1/music-app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :name, :ord)
  end
end

w5d1/music-app/app/helpers/tracks_helper.rb
module TracksHelper
end

w5d1/music-app/app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>


<form class='form' action="<%= action_url %>" method="POST" %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label for='track-name'>Name</label>
  <input id='track-name' type="text" name="track[name]" value="<%= track.name %>">
</p>

<p>
<label for='track-album'>Album</label>
  <select id='track-album' name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        <%= "selected" if track.album_id == album.id %>
        value="<%= album.id %>">
        <%= album.name %>
      </option>
    <% end %>
  </select>
</p>

<p>
  <label>Ord
  <input type="number" name="track[ord]" value="<%= track.ord %>">
  </label>
</p>

<p>
  <label for="track_bonus_f">Standard</label>
  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !track.bonus %>>
  <br>
  <label for="track_bonus_t">Bonus</label>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if track.bonus %>>
</p>

<p>
  <label for="track_lyrics">Lyrics</label><br>
  <textarea id="track_lyrics"
    rows="10" cols="40"
    name="track[lyrics]"><%= track.lyrics %></textarea>
</p>

  <input type="submit">
</form>

w5d1/music-app/app/views/tracks/edit.html.erb
<h1 class='page-header'>Edit <%= @track.name %></h1>

<%= render "form", track: @track %>

w5d1/music-app/app/views/tracks/new.html.erb
<h1 class='page-header'>New <%= @album.name %> Track</h1>

<%= render "form", track: @track %>

w5d1/music-app/app/views/tracks/show.html.erb
<h1 class='page-header'><%= @track.name %></h1>

<%= ugly_lyrics(@track.lyrics) %>

<%= render "note/form", track: @track %>

<h4 class='sub-header'>Notes</h4>

<% @track.notes.each do |note| %>
  <%= render "note/note", note: note %>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= edit_track_url(@track) %>">Edit Track</a></li>
  <li>
    <form action="<%= track_url(@track) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Track">
    </form>
  </li>
  <li><a class='button' href="<%= album_url(@track.album) %>"><%= @track.album.name %></a></li>
</ul>